
# 设置 Eureka Service1 端口 9090
server:
  port: 9090



spring:

  # 配置 Spring Boot 项目名称
  application:
    name: model-jiankong-eureka-service-1



eureka:


  instance:
    # 配置 Eureka 启动的地址
#    hostname: boke-eureka-service-1
    # 表示使用 ip 注册 Eureka Service 节点, 如果不配置为 true 则使用hostname进行注册
    ip-address: true


  client:
    # 是否将自己注册到 Eureka-service 在 Eureka 集群时开启
    register-with-eureka: false
    # 表示是否同步其他 Eureka Services 的节点信息, 表示是否从 Eureka Server 获取注册信息, 在 Eureka 集群时开启
    fetch-registry: false

#    service-url:
#      defaultZone: "http://eureka2:1112/eureka/"

