

# 配置 tomcat server 端口 8080
server:
  port: 8080






spring:


  # 配置 Spring Boot 应用名称
  application:
    name: user-view-display-data-model


  # Redis 地址配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: "12345"
    database: 0


  # thymeleaf 模板框架
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    encoding: UTF-8


  # 本地资源配置
  resources:
    static-locations: classpath:/static/css/, classpath:/static/script, calsspath:/static/images/

